// swift-tools-version: 5.9
import PackageDescription

// JoyDOM — public binary distribution.
// Generated by the "Release Swift binary" workflow in the source repo.
let package = Package(
    name: "JoyDOM",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "JoyDOM", targets: ["JoyDOM", "FlexLayout"]),
    ],
    targets: [
        .binaryTarget(
            name: "JoyDOM",
            url: "https://github.com/j0yhq/joydom-swift/releases/download/0.0.3-alpha/JoyDOM.xcframework.zip",
            checksum: "6cec6b5c13d0c40ffb97c9585366dfb50b9a968b5dcd1638f14e15cc5e5e8bf8"
        ),
        .binaryTarget(
            name: "FlexLayout",
            url: "https://github.com/j0yhq/joydom-swift/releases/download/0.0.3-alpha/FlexLayout.xcframework.zip",
            checksum: "61f4a36ea6745505b7781f8e44b7c43903d6f862890784855e9ffa3ffcc31b33"
        ),
    ]
)
