// swift-tools-version: 5.9
import PackageDescription

// JoyDOM — public binary distribution.
// Generated by the "Release Swift binary" workflow in the source repo.
let package = Package(
    name: "JoyDOM",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "JoyDOM", targets: ["JoyDOM", "FlexLayout"]),
    ],
    targets: [
        .binaryTarget(
            name: "JoyDOM",
            url: "https://github.com/j0yhq/joydom-swift/releases/download/0.0.5-alpha/JoyDOM.xcframework.zip",
            checksum: "4f7ab72c52be8bf5ad89f094d54841f3cef6d452876ef88a9df71fa1b2668268"
        ),
        .binaryTarget(
            name: "FlexLayout",
            url: "https://github.com/j0yhq/joydom-swift/releases/download/0.0.5-alpha/FlexLayout.xcframework.zip",
            checksum: "fa860954d28036541364a4589e459ceac1aa61e0f7632f8934320440ab761030"
        ),
    ]
)
