// swift-tools-version: 5.9
import PackageDescription

// JoyDOM — public binary distribution.
// Generated by the "Release Swift binary" workflow in the source repo.
let package = Package(
    name: "JoyDOM",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "JoyDOM", targets: ["JoyDOM", "FlexLayout"]),
    ],
    targets: [
        .binaryTarget(
            name: "JoyDOM",
            url: "https://github.com/j0yhq/joydom-swift/releases/download/0.0.2-alpha/JoyDOM.xcframework.zip",
            checksum: "e7f0e885c8b92571b121ffc4d9c85d643d57abe819b80581134e4169de5b856a"
        ),
        .binaryTarget(
            name: "FlexLayout",
            url: "https://github.com/j0yhq/joydom-swift/releases/download/0.0.2-alpha/FlexLayout.xcframework.zip",
            checksum: "30c983b1c1ef25e50510e9e34ffb480ae1b684f57dce5e5a966f0fcfc2a44dcc"
        ),
    ]
)
